image: dr.rechenknecht.net/bauhelfer/container/main/rust:ubuntu-jammy

stages:
  - prepare
  - build
  - lint
  - publish

variables:
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  PACKAGE_BASE_VERSION: "0.1"

prepare-rs:
  stage: prepare
  needs: []
  script:
     - export COMMIT_COUNT=`git rev-list --count HEAD`
     - sed -i "s/0.0.0-dev/${PACKAGE_BASE_VERSION}.${COMMIT_COUNT}-${CI_PIPELINE_IID}/g" pam/Cargo.toml
     - sed -i "s/0.0.0-dev/${PACKAGE_BASE_VERSION}.${COMMIT_COUNT}-${CI_PIPELINE_IID}/g" nss/Cargo.toml
     - sed -i "s/0.0.0-dev/${PACKAGE_BASE_VERSION}.${COMMIT_COUNT}-${CI_PIPELINE_IID}/g" guest-users-lib/Cargo.toml
     - sed -i "s/0.0.0-dev/${PACKAGE_BASE_VERSION}.${COMMIT_COUNT}-${CI_PIPELINE_IID}/g" sync-accountsservice/Cargo.toml
     - sed -i "s/0.0.0-dev/${PACKAGE_BASE_VERSION}.${COMMIT_COUNT}-${CI_PIPELINE_IID}/g" guest-warning/Cargo.toml
  artifacts:
    paths:
      - guest-users-lib/Cargo.toml
      - nss/Cargo.toml
      - pam/Cargo.toml
      - sync-accountsservice/Cargo.toml
      - guest-warning/Cargo.toml
    expire_in: 1 week
    when: always

lint-rs:
  stage: lint
  needs:
    - build-rs:ubuntu-jammy
  script:
    - apt-get update
    - apt-get install -q -y libsqlite3-dev libclang-dev libpam-dev libnss3-dev
    - rustup component add clippy
    - cargo clippy -- -Dwarnings
    - rustup component add rustfmt
    - cargo fmt --all -- --check

build-rs:ubuntu-jammy:
  stage: build
  needs:
    - prepare-rs
  script:
    # Allow getting schema.rs as artifact
    - rm guest-users-lib/src/db/.gitignore
    - apt-get update
    - apt-get install -q -y libsqlite3-dev dpkg dpkg-dev liblzma-dev libclang-dev libpam-dev libnss3-dev
    - cargo install cargo-deb
    - cargo install diesel_cli --no-default-features --features "sqlite"
    - diesel migration run --database-url=guest_users.db --config-file guest-users-lib/diesel.toml --migration-dir guest-users-lib/migrations
    - cargo deb -p guest-users-pam
    - cargo deb -p guest-users-nss
    - cargo deb -p guest-users-lib
    - cargo deb -p guest-users-sync-accountsservice
    - cargo deb -p guest-users-guest-warning
    - mkdir -p packages/ubuntu-jammy/main
    - cp target/debian/*.deb packages/ubuntu-jammy/main
  artifacts:
    paths:
      - packages/ubuntu-jammy/main
      - guest-users-lib/src/db/schema.rs
    expire_in: 1 week
    when: always

pages:
  stage: publish
  image: dr.rechenknecht.net/bauhelfer/container/main/aptly
  needs:
    - build-rs:ubuntu-jammy
  script:
    - apt-get update
    - mkdir -p public
    - aptly-ci-new-repo guest-users packages public/packages
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
