#!/bin/sh

set -e

case "$1" in
    failed-upgrade|remove|deconfigure)
        sed -i 's/ guest_users//g' /etc/nsswitch.conf
    ;;

    upgrade)
    ;;

    *)
        echo "prerm script called with unknown/unsupported argument \`$1'" >&2
        exit 1
    ;;
esac


